### ISSUE TITLE
Editing max HP of combatant not working

### ISSUE THREAD

**Issue by SondreElg** [valentine195/initiative-tracker#62]
When editing a creature in the Initiative Tracker, all fields except max HP is updated as expected.
This is true even when changing the creature the creature-entry is based off of, and when the creature-entry is not based on an existing creature.

Initiative Tracker 8.0.7
Obsidian 0.15.9

**Comment by valentine195** [comment]
Can you show me a screenshot of what you mean by max HP?

**Comment by SondreElg** [comment]
Before attempting to update HP (notice the value I'd trying to set in the HP field differing from the character's HP)
![image](https://user-images.githubusercontent.com/44784704/190938219-49c55478-9ed0-4daf-b11e-2204977b7a10.png)

After attempting to update HP (character's HP stays the same)
![image](https://user-images.githubusercontent.com/44784704/190938229-ed417129-f40f-4eef-bc29-673e6017c5a8.png)

Also, as a side note, it would be nice if the HP and initiative bonus of players would normally follow their statblocks as default if they're defined. This would mean uses who have statblocks defiend for their player characters won't have to update both their statblocks as well as in the initiative tracker.

This should probably be its own issue though, but thought it could be something to be conscious of when looking over this code.
